
package com.my.project.sample.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://www.example.org/myService/")
public interface IMyService {


    /**
     * 
     * @param num2
     * @param num1
     * @return
     *     returns int
     */
    @WebMethod(action = "http://www.example.org/myService/times")
    @WebResult(name = "timesResult", targetNamespace = "")
    @RequestWrapper(localName = "times", targetNamespace = "http://www.example.org/myService/", className = "com.my.project.sample.wsimport.Times")
    @ResponseWrapper(localName = "timesResponse", targetNamespace = "http://www.example.org/myService/", className = "com.my.project.sample.wsimport.TimesResponse")
    public int times(
    	@WebParam(name = "license", targetNamespace = "", header = true)
    	String license,
        @WebParam(name = "num1", targetNamespace = "")
        int num1,
        @WebParam(name = "num2", targetNamespace = "")
        int num2);

    /**
     * 
     * @param num2
     * @param num1
     * @return
     *     returns int
     */
    @WebMethod(action = "http://www.example.org/myService/divide")
    @WebResult(name = "divideResult", targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://www.example.org/myService/", className = "com.my.project.sample.wsimport.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://www.example.org/myService/", className = "com.my.project.sample.wsimport.DivideResponse")
    public int divide(
        @WebParam(name = "num1", targetNamespace = "")
        int num1,
        @WebParam(name = "num2", targetNamespace = "")
        int num2);

}
