//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.03 at 01:11:53 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/class", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.my.project.jaxws.xjc;
