
package com.my.project.soap.wsimport;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://project.my.com/webservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMyService {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://project.my.com/webservice", className = "com.my.project.soap.wsimport.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://project.my.com/webservice", className = "com.my.project.soap.wsimport.AddResponse")
    @Action(input = "http://project.my.com/webservice/IMyService/addRequest", output = "http://project.my.com/webservice/IMyService/addResponse")
    public Integer add(
        @WebParam(name = "a", targetNamespace = "")
        Integer a,
        @WebParam(name = "b", targetNamespace = "")
        Integer b);

    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://project.my.com/webservice", className = "com.my.project.soap.wsimport.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://project.my.com/webservice", className = "com.my.project.soap.wsimport.DeleteResponse")
    @Action(input = "http://project.my.com/webservice/IMyService/deleteRequest", output = "http://project.my.com/webservice/IMyService/deleteResponse")
    public void delete(
        @WebParam(name = "user", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<User> user);

    /**
     * 
     * @return
     *     returns java.util.List<com.my.project.soap.wsimport.User>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://project.my.com/webservice", className = "com.my.project.soap.wsimport.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://project.my.com/webservice", className = "com.my.project.soap.wsimport.ListResponse")
    @Action(input = "http://project.my.com/webservice/IMyService/listRequest", output = "http://project.my.com/webservice/IMyService/listResponse")
    public List<User> list();

    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://project.my.com/webservice", className = "com.my.project.soap.wsimport.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://project.my.com/webservice", className = "com.my.project.soap.wsimport.AddUserResponse")
    @Action(input = "http://project.my.com/webservice/IMyService/addUserRequest", output = "http://project.my.com/webservice/IMyService/addUserResponse")
    public void addUser(
        @WebParam(name = "user", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<User> user);

    /**
     * 
     * @param authInfo
     * @param parameters
     * @return
     *     returns com.my.project.soap.wsimport.AuthListResponse
     */
    @WebMethod
    @WebResult(name = "authListResponse", targetNamespace = "http://project.my.com/webservice", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://project.my.com/webservice/IMyService/authListRequest", output = "http://project.my.com/webservice/IMyService/authListResponse")
    public AuthListResponse authList(
        @WebParam(name = "authList", targetNamespace = "http://project.my.com/webservice", partName = "parameters")
        AuthList parameters,
        @WebParam(name = "authInfo", targetNamespace = "http://project.my.com/webservice", header = true, partName = "authInfo")
        String authInfo);

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns com.my.project.soap.wsimport.User
     * @throws UserException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://project.my.com/webservice", className = "com.my.project.soap.wsimport.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://project.my.com/webservice", className = "com.my.project.soap.wsimport.LoginResponse")
    @Action(input = "http://project.my.com/webservice/IMyService/loginRequest", output = "http://project.my.com/webservice/IMyService/loginResponse", fault = {
        @FaultAction(className = UserException_Exception.class, value = "http://project.my.com/webservice/IMyService/login/Fault/UserException")
    })
    public User login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws UserException_Exception
    ;

}
